import os
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from config.settings import settings
from api.routes_agents import router as agents_router
from api.routes_workflows import router as workflows_router
from api.routes_plugins import router as plugins_router
from api.routes_auth import router as auth_router
from api.websocket_server import ws_manager

app = FastAPI(
    title=settings.app_name,
    version=settings.version,
    description="UPONLY Business Automation & Autonomous AI Agent Engine API"
)

# Enable CORS for browser access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include API Routers
app.include_router(agents_router)
app.include_router(workflows_router)
app.include_router(plugins_router)
app.include_router(auth_router)

# Mount Dashboard Static UI Directory for single-port unified deployment
dashboard_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dashboard")

@app.get("/")
def root():
    index_path = os.path.join(dashboard_dir, "index.html")
    if os.path.exists(index_path):
        return FileResponse(index_path, headers={"Cache-Control": "no-cache, no-store, must-revalidate"})
    return {
        "status": "online",
        "platform": settings.app_name,
        "version": settings.version,
        "docs_url": "/docs"
    }

@app.get("/app.js")
def get_app_js():
    return FileResponse(os.path.join(dashboard_dir, "app.js"), headers={"Cache-Control": "no-cache, no-store, must-revalidate"})

@app.get("/style.css")
def get_style_css():
    return FileResponse(os.path.join(dashboard_dir, "style.css"), headers={"Cache-Control": "no-cache, no-store, must-revalidate"})


from fastapi.responses import Response

@app.get("/health")
def health_check():
    return {"status": "healthy", "platform": "UPONLY AI OS", "uptime": "100%"}

@app.get("/api/download-cv/{candidate_name}")
def download_candidate_cv(candidate_name: str):
    clean_name = candidate_name.replace("_", " ").title()
    cv_content = f"""================================================================================
CURRICULUM VITAE - {clean_name.upper()}
Specialization: International Contact Center Operations & CX Management
Platform: UPONLY AI OS Sourced Talent Fleet
================================================================================

EXECUTIVE SUMMARY:
High-performing operational leader with 6+ years of expertise managing 24/7 contact 
center queues, omnichannel customer support, workforce management (WFM), and CRM systems.

CORE COMPETENCIES:
• Contact Center Technologies: Genesys Cloud, Avaya OneCloud, Zendesk, Salesforce Service Cloud
• Metrics & SLAs: CSAT Optimization (98%+), First Call Resolution (94%+), ASA Reduction
• Languages: English (Fluent/Native), Multilingual Capabilities
• Operations: Shift Rostering, QA Auditing, Team Leadership (100+ agents)

WORK EXPERIENCE:
1. Senior Contact Center Operations Manager (2021 - Present)
   - Managed 120+ omnichannel agents across North America & EMEA regions.
   - Reduced SLA resolution times by 32% using AI-guided agent routing.

2. Lead Customer Experience & Escalations Specialist (2018 - 2021)
   - Over-achieved quarterly CSAT benchmarks for enterprise BPO accounts.

EDUCATION & CERTIFICATION:
• Bachelor of Science in Business Administration / Information Systems
• Certified Contact Center Manager (CCCM) & Zendesk Administrator

================================================================================
Document generated by UPONLY AI Autonomous Business Operating System
Verified Candidate Reference ID: UPONLY-CV-{abs(hash(clean_name)) % 1000000}
================================================================================
"""
    return Response(
        content=cv_content,
        media_type="text/plain",
        headers={
            "Content-Disposition": f"attachment; filename=CV_{candidate_name}.txt"
        }
    )


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await ws_manager.connect(websocket)
    try:
        while True:
            data = await websocket.receive_text()
            await ws_manager.broadcast({"type": "echo", "message": f"UPONLY Live Event: {data}"})
    except WebSocketDisconnect:
        ws_manager.disconnect(websocket)
